[tool.poetry]
name = "pat"
version = "0.1.0"
description = "A build automation tool written in Python."
authors = ["Luc Shelton <luc.shelton@arcanedreams.com>"]
readme = "README.md"
packages = [
    { include = "pat" },
    { include = "pat_tests" }
]

classifiers = [
  # How mature is this project? Common values are
  #   3 - Alpha
  #   4 - Beta
  #   5 - Production/Stable
  "Development Status :: 4 - Beta",

  # Indicate who your project is intended for
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Build Tools",

  # Pick your license as you wish (see also "license" above)
  "License :: OSI Approved :: MIT License",

  # Specify the Python versions you support here.
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]

[tool.poetry.scripts]
pat = 'pat.__main__:cli'

[tool.poetry.dependencies]
python = "^3.10"
rich-click = "^1.8.3"
click = "^8.1.7"
rich = "^13.7.1"
jsonschema = "^4.22.0"
pydantic = "^2.8.0"
questionary = "^2.0.1"
pyyaml = "^6.0.1"
emoji = "^2.12.1"

[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
pylint = "^3.2.5"

[tool.poetry.group.docs.dependencies]
sphinx = "^7.3.7"
sphinx-rtd-theme = "^2.0.0"

[tool.poetry.group.test.dependencies]
coverage = "^7.5.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry_bumpversion.file."pat/__init__.py"]
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'
